-- 1. Modify scholarships table to match new requirements
-- Remove unused columns
ALTER TABLE scholarships 
DROP COLUMN IF EXISTS amount,
DROP COLUMN IF EXISTS status;

-- Add new columns
ALTER TABLE scholarships 
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS requirements text,
ADD COLUMN IF NOT EXISTS deadline date;

-- Ensure title exists (it should, but good to be safe)
-- ALTER TABLE scholarships ADD COLUMN IF NOT EXISTS title text;

-- 2. Create the scholarship_applications table
CREATE TABLE IF NOT EXISTS scholarship_applications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    scholarship_id bigint references scholarships(id) on delete cascade not null,
    student_id text references students(student_id) on delete cascade not null, -- Assumes student_id is the PK of students
    student_name text, -- Cache name for easier display
    course text,       -- Cache course
    year_level text,   -- Cache year
    contact_number text, -- Cache contact
    email text,        -- Cache email
    status text default 'Applied',
    unique(scholarship_id, student_id)
);

-- 3. Enable RLS (Optional but recommended)
ALTER TABLE scholarship_applications ENABLE ROW LEVEL SECURITY;

-- Allow public/authenticated access (adjust policies as needed)
CREATE POLICY "Enable read/write for all" ON scholarship_applications FOR ALL USING (true);
