export const PASS_STATUS = 'Qualified for Interview (1st Choice)';
export const FAIL_STATUS = 'Failed';
export const APPROVED_STATUS = 'Approved for Enrollment';
export const ENROLLED_STATUS = 'Enrolled';
export const INTERVIEW_STATUS = 'Interview Scheduled';
export const UNSUCCESSFUL_STATUS = 'Application Unsuccessful';
export const BULK_PASS_TEMPLATE_HEADERS = ['reference_id', 'applicant_name'];
export const NAT_PAGE_SIZE = 25;
export const NAT_TABLE_SHELL_CLASS = 'flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm';
