-- Volunteer time log for approved CARE Peer Facilitators.
--
-- Neither existing table fits: event_attendance requires an event_id (this
-- work isn't tied to an event) and office_visits is the counseling logbook
-- (reason + status). Facilitators self-clock; staff read the log by date.
--
-- Hours are derived (time_out - time_in), never stored -- one source of truth.

CREATE TABLE public.peer_facilitator_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id character varying NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    time_in timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    time_out timestamp with time zone,
    CONSTRAINT peer_facilitator_attendance_time_order CHECK (time_out IS NULL OR time_out > time_in)
);

-- One open session per facilitator: a second time-in fails at the DB, so no
-- app-side "are you already clocked in" check is needed.
CREATE UNIQUE INDEX peer_facilitator_attendance_one_open_session
    ON public.peer_facilitator_attendance (student_id)
    WHERE time_out IS NULL;

-- Staff dashboard filters by date, students read their own history.
CREATE INDEX peer_facilitator_attendance_time_in_idx
    ON public.peer_facilitator_attendance (time_in DESC);

-- A student controls the request body, not just the row, so RLS alone can't stop
-- them posting time_in = 8 hours ago or time_out = next week and inflating their
-- hours. Stamp both server-side for students; staff corrections pass through.
-- Same pattern as stamp_peer_facilitator_school_year.
CREATE OR REPLACE FUNCTION public.stamp_peer_facilitator_attendance_times() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path = 'public'
    AS $$
BEGIN
    -- Non-students (Care Staff, Admin, service role) keep their supplied values.
    IF public.current_student_id() IS NULL THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' THEN
        NEW.time_in := now();
        NEW.time_out := NULL;  -- no clocking in already-closed with fabricated hours
        RETURN NEW;
    END IF;

    NEW.time_in := OLD.time_in;
    IF NEW.time_out IS NOT NULL THEN
        NEW.time_out := now();
    END IF;
    RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.stamp_peer_facilitator_attendance_times() FROM anon;

CREATE TRIGGER peer_facilitator_attendance_stamp_times
    BEFORE INSERT OR UPDATE ON public.peer_facilitator_attendance
    FOR EACH ROW
    EXECUTE FUNCTION public.stamp_peer_facilitator_attendance_times();

ALTER TABLE public.peer_facilitator_attendance ENABLE ROW LEVEL SECURITY;

-- Only students with an approved application in the ACTIVE form year may clock
-- in -- last year's facilitators can't keep logging hours.
CREATE POLICY "peer_facilitator_attendance_student_insert_own"
    ON public.peer_facilitator_attendance
    FOR INSERT
    TO authenticated
    WITH CHECK (
        student_id = public.current_student_id()
        AND EXISTS (
            SELECT 1
            FROM public.peer_facilitator_applications a
            WHERE a.student_id = peer_facilitator_attendance.student_id
              AND a.status = 'approved'
              AND a.school_year = (SELECT s.school_year FROM public.peer_facilitator_settings s WHERE s.id = 1)
        )
    );

CREATE POLICY "peer_facilitator_attendance_student_select_own"
    ON public.peer_facilitator_attendance
    FOR SELECT
    TO authenticated
    USING (student_id = public.current_student_id());

-- Students may only close an open session; a stamped row is immutable to them.
CREATE POLICY "peer_facilitator_attendance_student_close_own"
    ON public.peer_facilitator_attendance
    FOR UPDATE
    TO authenticated
    USING (student_id = public.current_student_id() AND time_out IS NULL)
    WITH CHECK (student_id = public.current_student_id());

CREATE POLICY "peer_facilitator_attendance_staff_select"
    ON public.peer_facilitator_attendance
    FOR SELECT
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

-- Staff can correct a bad row (forgotten time-out, duplicate).
CREATE POLICY "peer_facilitator_attendance_staff_write"
    ON public.peer_facilitator_attendance
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.peer_facilitator_attendance TO authenticated;
GRANT ALL ON public.peer_facilitator_attendance TO service_role;
