-- Student notifications are generated by staff/server workflows.
-- Students keep their existing own-row SELECT policy only.
DROP POLICY IF EXISTS notifications_student_insert_own ON public.notifications;
DROP POLICY IF EXISTS notifications_student_update_own ON public.notifications;
