CREATE TABLE IF NOT EXISTS public.dept_student_annotations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    department text NOT NULL REFERENCES public.departments(name) ON UPDATE CASCADE,
    note text NOT NULL DEFAULT '',
    is_at_risk boolean NOT NULL DEFAULT false,
    created_by text,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT dept_student_annotations_student_department_key UNIQUE (student_id, department),
    CONSTRAINT dept_student_annotations_note_length CHECK (char_length(note) <= 2000),
    CONSTRAINT dept_student_annotations_not_empty CHECK (is_at_risk OR btrim(note) <> '')
);

CREATE INDEX IF NOT EXISTS dept_student_annotations_department_idx
    ON public.dept_student_annotations (department);

CREATE INDEX IF NOT EXISTS dept_student_annotations_risk_idx
    ON public.dept_student_annotations (is_at_risk)
    WHERE is_at_risk = true;

CREATE INDEX IF NOT EXISTS dept_student_annotations_note_idx
    ON public.dept_student_annotations (student_id)
    WHERE btrim(note) <> '';

CREATE OR REPLACE FUNCTION public.set_dept_student_annotations_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    actor_label text := coalesce(
        public.current_staff_full_name(),
        public.current_staff_username(),
        public.current_staff_role()
    );
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    NEW.updated_by = actor_label;

    IF TG_OP = 'INSERT' THEN
        NEW.created_by = coalesce(NEW.created_by, actor_label);
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_dept_student_annotations_updated_at
    ON public.dept_student_annotations;

CREATE TRIGGER set_dept_student_annotations_updated_at
    BEFORE INSERT OR UPDATE ON public.dept_student_annotations
    FOR EACH ROW
    EXECUTE FUNCTION public.set_dept_student_annotations_updated_at();

ALTER TABLE public.dept_student_annotations ENABLE ROW LEVEL SECURITY;

CREATE POLICY dept_student_annotations_select_staff
    ON public.dept_student_annotations
    FOR SELECT
    TO authenticated
    USING (
        public.is_admin()
        OR public.current_staff_role() = 'Care Staff'::text
        OR (
            public.current_staff_role() = 'Department Head'::text
            AND department = public.current_staff_department()
            AND EXISTS (
                SELECT 1
                FROM public.students s
                WHERE s.id = dept_student_annotations.student_id
                  AND coalesce(s.department, ''::text) = coalesce(public.current_staff_department(), ''::text)
            )
        )
    );

CREATE POLICY dept_student_annotations_insert_department
    ON public.dept_student_annotations
    FOR INSERT
    TO authenticated
    WITH CHECK (
        public.is_admin()
        OR (
            public.current_staff_role() = 'Department Head'::text
            AND department = public.current_staff_department()
            AND EXISTS (
                SELECT 1
                FROM public.students s
                WHERE s.id = dept_student_annotations.student_id
                  AND coalesce(s.department, ''::text) = coalesce(public.current_staff_department(), ''::text)
            )
        )
    );

CREATE POLICY dept_student_annotations_update_department
    ON public.dept_student_annotations
    FOR UPDATE
    TO authenticated
    USING (
        public.is_admin()
        OR (
            public.current_staff_role() = 'Department Head'::text
            AND department = public.current_staff_department()
            AND EXISTS (
                SELECT 1
                FROM public.students s
                WHERE s.id = dept_student_annotations.student_id
                  AND coalesce(s.department, ''::text) = coalesce(public.current_staff_department(), ''::text)
            )
        )
    )
    WITH CHECK (
        public.is_admin()
        OR (
            public.current_staff_role() = 'Department Head'::text
            AND department = public.current_staff_department()
            AND EXISTS (
                SELECT 1
                FROM public.students s
                WHERE s.id = dept_student_annotations.student_id
                  AND coalesce(s.department, ''::text) = coalesce(public.current_staff_department(), ''::text)
            )
        )
    );

CREATE POLICY dept_student_annotations_delete_department
    ON public.dept_student_annotations
    FOR DELETE
    TO authenticated
    USING (
        public.is_admin()
        OR (
            public.current_staff_role() = 'Department Head'::text
            AND department = public.current_staff_department()
            AND EXISTS (
                SELECT 1
                FROM public.students s
                WHERE s.id = dept_student_annotations.student_id
                  AND coalesce(s.department, ''::text) = coalesce(public.current_staff_department(), ''::text)
            )
        )
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.dept_student_annotations TO authenticated;
GRANT ALL ON TABLE public.dept_student_annotations TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.dept_student_annotations_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dept_student_annotations_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION public.set_dept_student_annotations_updated_at() TO authenticated, service_role;
