-- Staff-built evaluation forms attached to events.
--
-- Deliberately separate from needs_assessment_* rather than sharing it: that
-- table set has exactly one reader policy ("any authenticated user may read an
-- active form"), which is wrong here -- an event evaluation must only reach
-- students who actually attended. Fresh tables get a policy written for the job.
--
-- Coexists with event_feedback (the fixed 7-question rating); it does not
-- replace it.

-- A form with event_id IS NULL is a reusable template; with an event_id it is
-- that event's live evaluation. UNIQUE(event_id) gives "one evaluation per
-- event" and unlimited templates in one index, because Postgres treats NULLs as
-- distinct. Attaching a template COPIES its rows, so editing a template later
-- can never change the meaning of answers already recorded.
CREATE TABLE public.event_evaluation_forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint REFERENCES public.events(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT event_evaluation_forms_title_len CHECK (char_length(title) BETWEEN 1 AND 200),
    CONSTRAINT event_evaluation_forms_description_len CHECK (description IS NULL OR char_length(description) <= 1000)
);

CREATE UNIQUE INDEX event_evaluation_forms_one_per_event
    ON public.event_evaluation_forms (event_id)
    WHERE event_id IS NOT NULL;

CREATE TABLE public.event_evaluation_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id bigint NOT NULL REFERENCES public.event_evaluation_forms(id) ON DELETE CASCADE,
    order_index integer NOT NULL DEFAULT 0,
    question_text text NOT NULL,
    question_type text NOT NULL,
    scale_min integer,
    scale_max integer,
    scale_min_label text,
    scale_max_label text,
    choices text[] NOT NULL DEFAULT '{}'::text[],
    is_required boolean NOT NULL DEFAULT true,
    CONSTRAINT event_evaluation_questions_text_len CHECK (char_length(question_text) BETWEEN 1 AND 500),
    CONSTRAINT event_evaluation_questions_type_chk CHECK (question_type = ANY (ARRAY['scale'::text, 'text'::text, 'choice'::text])),
    -- Each type carries its own required settings. Enforced here so a
    -- half-built question cannot reach a student's screen and render blank.
    CONSTRAINT event_evaluation_questions_shape_chk CHECK (
        CASE question_type
            WHEN 'choice' THEN coalesce(array_length(choices, 1), 0) >= 2
            WHEN 'scale' THEN scale_min IS NOT NULL AND scale_max IS NOT NULL AND scale_max > scale_min
            ELSE true
        END
    )
);

CREATE INDEX event_evaluation_questions_form_id_idx
    ON public.event_evaluation_questions (form_id, order_index);

-- Identity columns are a snapshot, not a join: a student's course and year
-- change between school years, and an evaluation must keep reading the way it
-- read on the day it was submitted. Stamped by trigger, never by the client.
CREATE TABLE public.event_evaluation_responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id bigint NOT NULL REFERENCES public.event_evaluation_forms(id) ON DELETE CASCADE,
    student_id character varying NOT NULL REFERENCES public.students(student_id) ON UPDATE CASCADE,
    student_name text,
    department text,
    course text,
    year_level text,
    submitted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT event_evaluation_responses_one_per_student UNIQUE (form_id, student_id)
);

CREATE INDEX event_evaluation_responses_form_id_idx
    ON public.event_evaluation_responses (form_id);

CREATE TABLE public.event_evaluation_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES public.event_evaluation_responses(id) ON DELETE CASCADE,
    question_id bigint NOT NULL REFERENCES public.event_evaluation_questions(id) ON DELETE CASCADE,
    answer_value integer,
    answer_text text,
    CONSTRAINT event_evaluation_answers_one_per_question UNIQUE (response_id, question_id),
    CONSTRAINT event_evaluation_answers_text_len CHECK (answer_text IS NULL OR char_length(answer_text) <= 1500)
);

CREATE INDEX event_evaluation_answers_response_id_idx
    ON public.event_evaluation_answers (response_id);

-- The student controls the request body, not just the row, so RLS alone cannot
-- stop them posting someone else's name or a flattering department. Stamp all
-- identity fields server-side for students; staff corrections pass through.
-- Same pattern as stamp_peer_facilitator_attendance_times.
CREATE OR REPLACE FUNCTION public.stamp_event_evaluation_response_identity() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path = 'public'
    AS $$
DECLARE
    v_student_id text := public.current_student_id();
BEGIN
    -- Non-students (Care Staff, Admin, service role) keep their supplied values.
    IF v_student_id IS NULL THEN
        RETURN NEW;
    END IF;

    NEW.student_id := v_student_id;
    NEW.submitted_at := now();

    SELECT trim(concat_ws(' ', s.first_name, s.last_name)), s.department, s.course, s.year_level
    INTO NEW.student_name, NEW.department, NEW.course, NEW.year_level
    FROM public.students s
    WHERE s.student_id = v_student_id;

    RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.stamp_event_evaluation_response_identity() FROM anon;

CREATE TRIGGER event_evaluation_responses_stamp_identity
    BEFORE INSERT ON public.event_evaluation_responses
    FOR EACH ROW
    EXECUTE FUNCTION public.stamp_event_evaluation_response_identity();

ALTER TABLE public.event_evaluation_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_evaluation_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_evaluation_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_evaluation_answers ENABLE ROW LEVEL SECURITY;

-- Reused by every student-facing policy below: attended the event and timed out.
CREATE OR REPLACE FUNCTION public.student_may_evaluate_form(p_form_id bigint) RETURNS boolean
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = 'public'
    AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.event_evaluation_forms f
        JOIN public.event_attendance a ON a.event_id = f.event_id
        WHERE f.id = p_form_id
          AND f.event_id IS NOT NULL
          AND f.is_active
          AND a.student_id = public.current_student_id()
          AND a.time_out IS NOT NULL
    );
$$;

REVOKE EXECUTE ON FUNCTION public.student_may_evaluate_form(bigint) FROM anon;

-- Forms: staff manage everything; a student sees only the evaluation for an
-- event they attended. Templates (event_id IS NULL) are structurally invisible
-- to students -- there is no policy that can return one.
CREATE POLICY "event_evaluation_forms_staff_all"
    ON public.event_evaluation_forms
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "event_evaluation_forms_student_read_attended"
    ON public.event_evaluation_forms
    FOR SELECT
    TO authenticated
    USING (public.student_may_evaluate_form(id));

CREATE POLICY "event_evaluation_questions_staff_all"
    ON public.event_evaluation_questions
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "event_evaluation_questions_student_read"
    ON public.event_evaluation_questions
    FOR SELECT
    TO authenticated
    USING (public.student_may_evaluate_form(form_id));

CREATE POLICY "event_evaluation_responses_staff_all"
    ON public.event_evaluation_responses
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "event_evaluation_responses_student_insert_own"
    ON public.event_evaluation_responses
    FOR INSERT
    TO authenticated
    WITH CHECK (student_id = public.current_student_id() AND public.student_may_evaluate_form(form_id));

CREATE POLICY "event_evaluation_responses_student_read_own"
    ON public.event_evaluation_responses
    FOR SELECT
    TO authenticated
    USING (student_id = public.current_student_id());

CREATE POLICY "event_evaluation_answers_staff_all"
    ON public.event_evaluation_answers
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "event_evaluation_answers_student_insert_own"
    ON public.event_evaluation_answers
    FOR INSERT
    TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.event_evaluation_responses r
        WHERE r.id = event_evaluation_answers.response_id
          AND r.student_id = public.current_student_id()
    ));

CREATE POLICY "event_evaluation_answers_student_read_own"
    ON public.event_evaluation_answers
    FOR SELECT
    TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.event_evaluation_responses r
        WHERE r.id = event_evaluation_answers.response_id
          AND r.student_id = public.current_student_id()
    ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_evaluation_forms TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_evaluation_questions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_evaluation_responses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_evaluation_answers TO authenticated;
GRANT ALL ON public.event_evaluation_forms TO service_role;
GRANT ALL ON public.event_evaluation_questions TO service_role;
GRANT ALL ON public.event_evaluation_responses TO service_role;
GRANT ALL ON public.event_evaluation_answers TO service_role;

-- Governance rows for the Admin permissions screen. Plain INSERT rather than a
-- seed-function rewrite, matching 20260706083000_seed_student_volunteer_feature_permission.
-- ponytail: these are display-only -- canAccessTable is never called; RLS above is the real gate.
INSERT INTO public.role_permissions (role, permission_type, permission_key, is_allowed, status, description)
VALUES
    ('Care Staff', 'table', 'event_evaluation_forms', true, 'enabled', 'Event evaluation form and template definitions.'),
    ('Care Staff', 'table', 'event_evaluation_questions', true, 'enabled', 'Event evaluation question definitions.'),
    ('Care Staff', 'table', 'event_evaluation_responses', true, 'enabled', 'Event evaluation submission records.'),
    ('Care Staff', 'table', 'event_evaluation_answers', true, 'enabled', 'Event evaluation per-question response records.'),
    ('Student', 'table', 'event_evaluation_forms', true, 'enabled', 'Event evaluation form and template definitions.'),
    ('Student', 'table', 'event_evaluation_questions', true, 'enabled', 'Event evaluation question definitions.'),
    ('Student', 'table', 'event_evaluation_responses', true, 'enabled', 'Event evaluation submission records.'),
    ('Student', 'table', 'event_evaluation_answers', true, 'enabled', 'Event evaluation per-question response records.'),
    ('Student', 'action', 'complete_event_evaluation', true, 'enabled', 'Submit the evaluation form attached to an attended event.')
ON CONFLICT (role, permission_type, permission_key) DO NOTHING;
