-- Counseling session + open evaluations.
--
-- Mirrors the event_evaluation_* design on purpose: staff build one evaluation
-- form (scale / text / choice questions) and students answer it once per
-- completed counseling session. The same form also backs "open evaluations" --
-- students who were counseled outside the digital workflow record their session
-- themselves on the public portal, identified by Student ID alone, exactly like
-- the public events portal.
--
-- Layout:
--   * counseling_evaluation_forms   -- ONE global form (is_global = true,
--                                      counseling_request_id = NULL) plus
--                                      optional reusable templates.
--   * counseling_evaluation_questions
--   * counseling_evaluation_responses  -- counseling_request_id NULL marks an
--                                        "open evaluation" recorded outside the
--                                        system counseling flow.
--   * counseling_evaluation_answers
--
-- Coexists with counseling_requests.feedback (the free-text general feedback);
-- it does not replace it.

CREATE TABLE IF NOT EXISTS public.counseling_evaluation_forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counseling_request_id bigint REFERENCES public.counseling_requests(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    is_global boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT counseling_evaluation_forms_title_len CHECK (char_length(title) BETWEEN 1 AND 200),
    CONSTRAINT counseling_evaluation_forms_description_len CHECK (description IS NULL OR char_length(description) <= 1000)
);

-- Exactly one global form. A row with is_global = true always has
-- counseling_request_id NULL (a request-linked form is per-request, not global).
CREATE UNIQUE INDEX IF NOT EXISTS counseling_evaluation_forms_one_global
    ON public.counseling_evaluation_forms (is_global)
    WHERE is_global = true;

-- One evaluation per counseling request (reserved for future per-request forms).
CREATE UNIQUE INDEX IF NOT EXISTS counseling_evaluation_forms_one_per_request
    ON public.counseling_evaluation_forms (counseling_request_id)
    WHERE counseling_request_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.counseling_evaluation_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id bigint NOT NULL REFERENCES public.counseling_evaluation_forms(id) ON DELETE CASCADE,
    order_index integer NOT NULL DEFAULT 0,
    question_text text NOT NULL,
    question_type text NOT NULL,
    scale_min integer,
    scale_max integer,
    scale_min_label text,
    scale_max_label text,
    choices text[] NOT NULL DEFAULT '{}'::text[],
    is_required boolean NOT NULL DEFAULT true,
    CONSTRAINT counseling_evaluation_questions_text_len CHECK (char_length(question_text) BETWEEN 1 AND 500),
    CONSTRAINT counseling_evaluation_questions_type_chk CHECK (question_type = ANY (ARRAY['scale'::text, 'text'::text, 'choice'::text])),
    -- Each type carries its own required settings, enforced here so a half-built
    -- question cannot reach a student's screen and render blank.
    CONSTRAINT counseling_evaluation_questions_shape_chk CHECK (
        CASE question_type
            WHEN 'choice' THEN coalesce(array_length(choices, 1), 0) >= 2
            WHEN 'scale' THEN scale_min IS NOT NULL AND scale_max IS NOT NULL AND scale_max > scale_min
            ELSE true
        END
    )
);

CREATE INDEX IF NOT EXISTS counseling_evaluation_questions_form_id_idx
    ON public.counseling_evaluation_questions (form_id, order_index);


-- Identity columns are a snapshot, not a join: a student's course and year
-- change between school years, and an evaluation must keep reading the way it
-- read on the day it was submitted. Stamped by trigger, never by the client.
-- counseling_request_id IS NULL means the response is an open evaluation --
-- recorded for a session that did not go through the system counseling flow.
CREATE TABLE IF NOT EXISTS public.counseling_evaluation_responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id bigint NOT NULL REFERENCES public.counseling_evaluation_forms(id) ON DELETE CASCADE,
    counseling_request_id bigint REFERENCES public.counseling_requests(id) ON DELETE CASCADE,
    student_id character varying NOT NULL REFERENCES public.students(student_id) ON UPDATE CASCADE,
    student_name text,
    department text,
    course text,
    year_level text,
    submitted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- One evaluation per system session. Open evaluations have no unique guard on
-- purpose: a student may record several outside-system sessions over time.
CREATE UNIQUE INDEX IF NOT EXISTS counseling_evaluation_responses_one_per_request
    ON public.counseling_evaluation_responses (counseling_request_id)
    WHERE counseling_request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS counseling_evaluation_responses_form_id_idx
    ON public.counseling_evaluation_responses (form_id);

CREATE INDEX IF NOT EXISTS counseling_evaluation_responses_student_id_idx
    ON public.counseling_evaluation_responses (student_id);

CREATE TABLE IF NOT EXISTS public.counseling_evaluation_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id bigint NOT NULL REFERENCES public.counseling_evaluation_responses(id) ON DELETE CASCADE,
    question_id bigint NOT NULL REFERENCES public.counseling_evaluation_questions(id) ON DELETE CASCADE,
    answer_value integer,
    answer_text text,
    CONSTRAINT counseling_evaluation_answers_one_per_question UNIQUE (response_id, question_id),
    CONSTRAINT counseling_evaluation_answers_text_len CHECK (answer_text IS NULL OR char_length(answer_text) <= 1500)
);

CREATE INDEX IF NOT EXISTS counseling_evaluation_answers_response_id_idx
    ON public.counseling_evaluation_answers (response_id);

-- The student controls the request body, not just the row, so RLS alone cannot
-- stop them posting someone else's name or a flattering department. Stamp all
-- identity fields server-side. For students the snapshot comes from the session;
-- for staff/RPC writes (open evaluations, public portal) it is resolved from the
-- supplied student_id so the identity is still trustworthy.
CREATE OR REPLACE FUNCTION public.stamp_counseling_evaluation_response_identity() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path = 'public'
    AS $$
DECLARE
    v_student public.students;
    v_student_id text := public.current_student_id();
BEGIN
    -- Non-students (Care Staff, Admin, RPCs, service role) supply the student_id.
    IF v_student_id IS NULL THEN
        v_student_id := NEW.student_id;
    END IF;

    SELECT *
    INTO v_student
    FROM public.students s
    WHERE s.student_id = v_student_id;

    IF v_student.student_id IS NOT NULL THEN
        NEW.student_id := v_student.student_id;
        NEW.student_name := trim(concat_ws(' ', v_student.first_name, v_student.middle_name, v_student.last_name, v_student.suffix));
        NEW.department := v_student.department;
        NEW.course := v_student.course;
        NEW.year_level := v_student.year_level;
    END IF;

    NEW.submitted_at := now();
    RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.stamp_counseling_evaluation_response_identity() FROM anon;

DROP TRIGGER IF EXISTS counseling_evaluation_responses_stamp_identity ON public.counseling_evaluation_responses;
CREATE TRIGGER counseling_evaluation_responses_stamp_identity
    BEFORE INSERT ON public.counseling_evaluation_responses
    FOR EACH ROW
    EXECUTE FUNCTION public.stamp_counseling_evaluation_response_identity();

ALTER TABLE public.counseling_evaluation_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.counseling_evaluation_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.counseling_evaluation_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.counseling_evaluation_answers ENABLE ROW LEVEL SECURITY;


-- Reused by every student-facing policy below: the linked counseling request is
-- the student's own AND the session is Completed AND the global form is active.
CREATE OR REPLACE FUNCTION public.student_may_evaluate_counseling(p_request_id bigint) RETURNS boolean
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = 'public'
    AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.counseling_requests r
        JOIN public.counseling_evaluation_forms f ON f.is_global
        WHERE r.id = p_request_id
          AND r.student_id = public.current_student_id()
          AND r.status = 'Completed'
          AND f.is_active
    );
$$;

REVOKE EXECUTE ON FUNCTION public.student_may_evaluate_counseling(bigint) FROM anon;

-- A student may see the active global form only once they have a completed
-- session of their own. Templates / per-request forms are structurally invisible
-- to students -- no policy can return one.
CREATE OR REPLACE FUNCTION public.student_has_completed_counseling() RETURNS boolean
    LANGUAGE sql
    STABLE
    SECURITY DEFINER
    SET search_path = 'public'
    AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.counseling_requests r
        WHERE r.student_id = public.current_student_id()
          AND r.status = 'Completed'
    );
$$;

REVOKE EXECUTE ON FUNCTION public.student_has_completed_counseling() FROM anon;

-- Drop existing policies if any to ensure clean idempotent creation
DROP POLICY IF EXISTS "counseling_evaluation_forms_staff_all" ON public.counseling_evaluation_forms;
DROP POLICY IF EXISTS "counseling_evaluation_forms_dept_read" ON public.counseling_evaluation_forms;
DROP POLICY IF EXISTS "counseling_evaluation_forms_student_read" ON public.counseling_evaluation_forms;

DROP POLICY IF EXISTS "counseling_evaluation_questions_staff_all" ON public.counseling_evaluation_questions;
DROP POLICY IF EXISTS "counseling_evaluation_questions_dept_read" ON public.counseling_evaluation_questions;
DROP POLICY IF EXISTS "counseling_evaluation_questions_student_read" ON public.counseling_evaluation_questions;

DROP POLICY IF EXISTS "counseling_evaluation_responses_staff_all" ON public.counseling_evaluation_responses;
DROP POLICY IF EXISTS "counseling_evaluation_responses_dept_read" ON public.counseling_evaluation_responses;
DROP POLICY IF EXISTS "counseling_evaluation_responses_student_insert_own" ON public.counseling_evaluation_responses;
DROP POLICY IF EXISTS "counseling_evaluation_responses_student_read_own" ON public.counseling_evaluation_responses;

DROP POLICY IF EXISTS "counseling_evaluation_answers_staff_all" ON public.counseling_evaluation_answers;
DROP POLICY IF EXISTS "counseling_evaluation_answers_dept_read" ON public.counseling_evaluation_answers;
DROP POLICY IF EXISTS "counseling_evaluation_answers_student_insert_own" ON public.counseling_evaluation_answers;
DROP POLICY IF EXISTS "counseling_evaluation_answers_student_read_own" ON public.counseling_evaluation_answers;

-- Forms: staff manage everything; dept reads (to view their students' results);
-- a student sees only the active global form when they have a completed session.
CREATE POLICY "counseling_evaluation_forms_staff_all"
    ON public.counseling_evaluation_forms
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "counseling_evaluation_forms_dept_read"
    ON public.counseling_evaluation_forms
    FOR SELECT
    TO authenticated
    USING (public.current_staff_role() = 'Department Head'::text);

CREATE POLICY "counseling_evaluation_forms_student_read"
    ON public.counseling_evaluation_forms
    FOR SELECT
    TO authenticated
    USING (is_global = true AND is_active = true AND public.student_has_completed_counseling());

CREATE POLICY "counseling_evaluation_questions_staff_all"
    ON public.counseling_evaluation_questions
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "counseling_evaluation_questions_dept_read"
    ON public.counseling_evaluation_questions
    FOR SELECT
    TO authenticated
    USING (public.current_staff_role() = 'Department Head'::text);

CREATE POLICY "counseling_evaluation_questions_student_read"
    ON public.counseling_evaluation_questions
    FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.counseling_evaluation_forms f
            WHERE f.id = form_id
              AND f.is_global
              AND f.is_active
              AND public.student_has_completed_counseling()
        )
    );

-- Responses: staff manage everything (incl. reading open evaluations); dept
-- reads only their department's students; a student inserts/reads only their own
-- Completed-session responses (open rows are staff/RPC territory).
CREATE POLICY "counseling_evaluation_responses_staff_all"
    ON public.counseling_evaluation_responses
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "counseling_evaluation_responses_dept_read"
    ON public.counseling_evaluation_responses
    FOR SELECT
    TO authenticated
    USING (public.current_staff_role() = 'Department Head'::text AND department = public.current_staff_department());

CREATE POLICY "counseling_evaluation_responses_student_insert_own"
    ON public.counseling_evaluation_responses
    FOR INSERT
    TO authenticated
    WITH CHECK (
        student_id = public.current_student_id()
        AND counseling_request_id IS NOT NULL
        AND form_id = (SELECT id FROM public.counseling_evaluation_forms WHERE is_global = true LIMIT 1)
        AND public.student_may_evaluate_counseling(counseling_request_id)
    );

CREATE POLICY "counseling_evaluation_responses_student_read_own"
    ON public.counseling_evaluation_responses
    FOR SELECT
    TO authenticated
    USING (student_id = public.current_student_id());

CREATE POLICY "counseling_evaluation_answers_staff_all"
    ON public.counseling_evaluation_answers
    FOR ALL
    TO authenticated
    USING (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text)
    WITH CHECK (public.is_admin() OR public.current_staff_role() = 'Care Staff'::text);

CREATE POLICY "counseling_evaluation_answers_dept_read"
    ON public.counseling_evaluation_answers
    FOR SELECT
    TO authenticated
    USING (
        public.current_staff_role() = 'Department Head'::text
        AND EXISTS (
            SELECT 1 FROM public.counseling_evaluation_responses r
            WHERE r.id = counseling_evaluation_answers.response_id
              AND r.department = public.current_staff_department()
        )
    );

CREATE POLICY "counseling_evaluation_answers_student_insert_own"
    ON public.counseling_evaluation_answers
    FOR INSERT
    TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.counseling_evaluation_responses r
        WHERE r.id = counseling_evaluation_answers.response_id
          AND r.student_id = public.current_student_id()
          AND r.counseling_request_id IS NOT NULL
    ));

CREATE POLICY "counseling_evaluation_answers_student_read_own"
    ON public.counseling_evaluation_answers
    FOR SELECT
    TO authenticated
    USING (EXISTS (
        SELECT 1 FROM public.counseling_evaluation_responses r
        WHERE r.id = counseling_evaluation_answers.response_id
          AND r.student_id = public.current_student_id()
    ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.counseling_evaluation_forms TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.counseling_evaluation_questions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.counseling_evaluation_responses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.counseling_evaluation_answers TO authenticated;
GRANT ALL ON public.counseling_evaluation_forms TO service_role;
GRANT ALL ON public.counseling_evaluation_questions TO service_role;
GRANT ALL ON public.counseling_evaluation_responses TO service_role;
GRANT ALL ON public.counseling_evaluation_answers TO service_role;

-- Governance rows for the Admin permissions screen. Display-only -- RLS above is
-- the real gate (same convention as the event evaluations migration).
INSERT INTO public.role_permissions (role, permission_type, permission_key, is_allowed, status, description)
VALUES
    ('Care Staff', 'table', 'counseling_evaluation_forms', true, 'enabled', 'Counseling evaluation form and template definitions.'),
    ('Care Staff', 'table', 'counseling_evaluation_questions', true, 'enabled', 'Counseling evaluation question definitions.'),
    ('Care Staff', 'table', 'counseling_evaluation_responses', true, 'enabled', 'Counseling evaluation submission records.'),
    ('Care Staff', 'table', 'counseling_evaluation_answers', true, 'enabled', 'Counseling evaluation per-question response records.'),
    ('Care Staff', 'action', 'record_open_counseling_evaluation', true, 'enabled', 'Record counseling evaluations conducted outside the system.'),
    ('Department Head', 'table', 'counseling_evaluation_forms', true, 'enabled', 'Counseling evaluation form and template definitions.'),
    ('Department Head', 'table', 'counseling_evaluation_questions', true, 'enabled', 'Counseling evaluation question definitions.'),
    ('Department Head', 'table', 'counseling_evaluation_responses', true, 'enabled', 'Counseling evaluation submission records.'),
    ('Department Head', 'table', 'counseling_evaluation_answers', true, 'enabled', 'Counseling evaluation per-question response records.'),
    ('Student', 'table', 'counseling_evaluation_forms', true, 'enabled', 'Counseling evaluation form and template definitions.'),
    ('Student', 'table', 'counseling_evaluation_questions', true, 'enabled', 'Counseling evaluation question definitions.'),
    ('Student', 'table', 'counseling_evaluation_responses', true, 'enabled', 'Counseling evaluation submission records.'),
    ('Student', 'table', 'counseling_evaluation_answers', true, 'enabled', 'Counseling evaluation per-question response records.'),
    ('Student', 'action', 'complete_counseling_evaluation', true, 'enabled', 'Submit the evaluation for a completed counseling session.')
ON CONFLICT (role, permission_type, permission_key) DO NOTHING;


-- ---------------------------------------------------------------------------
-- Public portal RPCs. Same trust model as the public events portal: the student
-- is identified by Student ID alone, everything else is resolved server-side,
-- and the browser never receives a roster (an ID reveals nothing).
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.public_get_counseling_evaluations(text);

CREATE FUNCTION public.public_get_counseling_evaluations(p_student_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_student public.students;
    v_sessions jsonb;
    v_open_count integer;
BEGIN
    v_student := public.public_resolve_student(p_student_id);
    IF v_student.student_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Student ID was not found.');
    END IF;

    -- Only what the student needs to pick a session to evaluate: id + dates +
    -- whether it was already evaluated. No notes, no counselor, no description.
    SELECT coalesce(jsonb_agg(x ORDER BY x.created_at DESC), '[]'::jsonb)
    INTO v_sessions
    FROM (
        SELECT jsonb_build_object(
            'request_id', r.id,
            'created_at', r.created_at,
            'scheduled_date', r.scheduled_date,
            'evaluated', EXISTS (
                SELECT 1 FROM public.counseling_evaluation_responses er
                WHERE er.counseling_request_id = r.id
            )
        ) AS x
        FROM public.counseling_requests r
        WHERE r.student_id = v_student.student_id
          AND r.status = 'Completed'
    ) q;

    SELECT count(*) INTO v_open_count
    FROM public.counseling_evaluation_responses er
    WHERE er.student_id = v_student.student_id
      AND er.counseling_request_id IS NULL;

    RETURN jsonb_build_object(
        'success', true,
        'sessions', v_sessions,
        'open_count', v_open_count
    );
END;
$$;

DROP FUNCTION IF EXISTS public.public_get_counseling_evaluation_form(bigint);

CREATE FUNCTION public.public_get_counseling_evaluation_form(p_request_id bigint DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_form public.counseling_evaluation_forms;
    v_questions jsonb;
BEGIN
    -- If linked to a request, verify request is Completed
    IF p_request_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.counseling_requests r
        WHERE r.id = p_request_id AND r.status = 'Completed'
    ) THEN
        RETURN jsonb_build_object('success', false, 'error', 'This counseling session is not available for evaluation.');
    END IF;

    SELECT * INTO v_form
    FROM public.counseling_evaluation_forms
    WHERE is_global = true AND is_active = true
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'No counseling evaluation form is available right now.');
    END IF;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', q.id,
            'order_index', q.order_index,
            'question_text', q.question_text,
            'question_type', q.question_type,
            'scale_min', q.scale_min,
            'scale_max', q.scale_max,
            'scale_min_label', q.scale_min_label,
            'scale_max_label', q.scale_max_label,
            'choices', q.choices,
            'is_required', q.is_required
        ) ORDER BY q.order_index
    )
    INTO v_questions
    FROM public.counseling_evaluation_questions q
    WHERE q.form_id = v_form.id;

    RETURN jsonb_build_object(
        'success', true,
        'form', jsonb_build_object('id', v_form.id, 'title', v_form.title, 'description', v_form.description),
        'questions', coalesce(v_questions, '[]'::jsonb)
    );
END;
$$;

DROP FUNCTION IF EXISTS public.public_counseling_evaluate(text, bigint, jsonb);

CREATE FUNCTION public.public_counseling_evaluate(
    p_student_id text,
    p_request_id bigint,
    p_answers jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_student public.students;
    v_form public.counseling_evaluation_forms;
    v_response_id bigint;
    v_answer jsonb;
    v_answered integer;
    v_expected integer;
BEGIN
    v_student := public.public_resolve_student(p_student_id);
    IF v_student.student_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'Student ID was not found.');
    END IF;

    IF NOT public.public_throttle_take(v_student.student_id, 'counseling_evaluate', 2, interval '5 minutes') THEN
        RETURN jsonb_build_object('success', false, 'error', 'Too many attempts. Please wait a few minutes and try again.');
    END IF;

    IF jsonb_typeof(coalesce(p_answers, 'null'::jsonb)) <> 'array'
       OR jsonb_array_length(p_answers) = 0
       OR jsonb_array_length(p_answers) > 200 THEN
        RETURN jsonb_build_object('success', false, 'error', 'Answer every question before submitting.');
    END IF;

    SELECT * INTO v_form
    FROM public.counseling_evaluation_forms
    WHERE is_global = true AND is_active = true
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'No counseling evaluation form is available right now.');
    END IF;

    -- Session-linked path: the session must be the student's own and Completed,
    -- and it must not have been evaluated yet.
    IF p_request_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.counseling_requests r
            WHERE r.id = p_request_id
              AND r.student_id = v_student.student_id
              AND r.status = 'Completed'
        ) THEN
            RETURN jsonb_build_object('success', false, 'error', 'This counseling session is not available for evaluation.');
        END IF;

        IF EXISTS (
            SELECT 1 FROM public.counseling_evaluation_responses er
            WHERE er.counseling_request_id = p_request_id
        ) THEN
            RETURN jsonb_build_object('success', false, 'error', 'You have already evaluated this session.');
        END IF;
    END IF;

    -- A blank submission is rejected outright: every question on the form needs
    -- an answer that is actually present, not just a key with an empty value.
    SELECT count(*) INTO v_expected
    FROM public.counseling_evaluation_questions
    WHERE form_id = v_form.id;

    SELECT count(DISTINCT (a->>'question_id')::bigint) INTO v_answered
    FROM jsonb_array_elements(p_answers) a
    WHERE (a->>'question_id') ~ '^[0-9]+$'
      AND (
          nullif(a->>'answer_value', '') IS NOT NULL
          OR nullif(trim(coalesce(a->>'answer_text', '')), '') IS NOT NULL
      )
      AND EXISTS (
          SELECT 1 FROM public.counseling_evaluation_questions q
          WHERE q.form_id = v_form.id AND q.id = (a->>'question_id')::bigint
      );

    IF v_answered < v_expected THEN
        RETURN jsonb_build_object('success', false, 'error', 'Answer every question before submitting.');
    END IF;

    INSERT INTO public.counseling_evaluation_responses (
        form_id, counseling_request_id, student_id, student_name, department, course, year_level, submitted_at
    ) VALUES (
        v_form.id,
        p_request_id,
        v_student.student_id,
        trim(concat_ws(' ', v_student.first_name, v_student.middle_name, v_student.last_name, v_student.suffix)),
        v_student.department,
        v_student.course,
        v_student.year_level,
        now()
    ) RETURNING id INTO v_response_id;

    FOR v_answer IN SELECT * FROM jsonb_array_elements(p_answers)
    LOOP
        IF (v_answer->>'question_id') !~ '^[0-9]+$' THEN
            CONTINUE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM public.counseling_evaluation_questions q
            WHERE q.form_id = v_form.id AND q.id = (v_answer->>'question_id')::bigint
        ) THEN
            CONTINUE;
        END IF;

        INSERT INTO public.counseling_evaluation_answers (response_id, question_id, answer_value, answer_text)
        VALUES (
            v_response_id,
            (v_answer->>'question_id')::bigint,
            CASE WHEN (v_answer->>'answer_value') ~ '^-?[0-9]+$'
                THEN (v_answer->>'answer_value')::integer END,
            left(nullif(trim(coalesce(v_answer->>'answer_text', '')), ''), 1500)
        );
    END LOOP;

    RETURN jsonb_build_object('success', true);
END;
$$;

REVOKE ALL ON FUNCTION public.public_get_counseling_evaluations(text) FROM public;
REVOKE ALL ON FUNCTION public.public_get_counseling_evaluation_form(bigint) FROM public;
REVOKE ALL ON FUNCTION public.public_counseling_evaluate(text, bigint, jsonb) FROM public;

GRANT EXECUTE ON FUNCTION public.public_get_counseling_evaluations(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.public_get_counseling_evaluation_form(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.public_counseling_evaluate(text, bigint, jsonb) TO anon, authenticated;
