-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admission_schedules (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  date date NOT NULL UNIQUE,
  venue text,
  slots integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  time_windows jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT admission_schedules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.answers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  submission_id bigint,
  question_id bigint,
  answer_value integer,
  answer_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT answers_pkey PRIMARY KEY (id),
  CONSTRAINT answers_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_id text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  email text NOT NULL UNIQUE,
  mobile text NOT NULL,
  priority_course text NOT NULL,
  test_date date NOT NULL,
  username text NOT NULL UNIQUE,
  status text DEFAULT 'Submitted'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  civil_status text,
  nationality text,
  reason text,
  street text,
  city text,
  province text,
  zip_code text,
  alt_course_1 text,
  alt_course_2 text,
  student_id text,
  suffix text,
  place_of_birth text,
  age integer,
  sex text,
  gender_identity text,
  facebook_url text,
  dob date,
  current_choice integer DEFAULT 1,
  interview_date text,
  test_time text,
  time_in timestamp with time zone,
  time_out timestamp with time zone,
  interview_queue_status text CHECK (interview_queue_status IS NULL OR interview_queue_status = 'Absent'::text),
  interview_venue text,
  interview_panel text,
  nat_password_hash text,
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_priority_course_fkey FOREIGN KEY (priority_course) REFERENCES public.courses(name),
  CONSTRAINT applications_alt_course_1_fkey FOREIGN KEY (alt_course_1) REFERENCES public.courses(name),
  CONSTRAINT applications_alt_course_2_fkey FOREIGN KEY (alt_course_2) REFERENCES public.courses(name),
  CONSTRAINT applications_test_date_fkey FOREIGN KEY (test_date) REFERENCES public.admission_schedules(date),
  CONSTRAINT applications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.audit_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_name text,
  action text,
  details text,
  created_at timestamp with time zone DEFAULT now(),
  actor_role text,
  actor_id text,
  actor_department text,
  entity_table text,
  entity_id text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.counseling_requests (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  student_id text,
  student_name text,
  request_type text,
  description text,
  status text DEFAULT 'Pending'::text,
  scheduled_date timestamp with time zone,
  department text,
  resolution_notes text,
  confidential_notes text,
  feedback text,
  rating integer,
  course_year text,
  contact_number text,
  reason_for_referral text,
  personal_actions_taken text,
  date_duration_of_concern text,
  referred_by text,
  referrer_contact_number text,
  relationship_with_student text,
  actions_made text,
  date_duration_of_observations text,
  referrer_signature text,
  CONSTRAINT counseling_requests_pkey PRIMARY KEY (id),
  CONSTRAINT counseling_requests_department_fkey FOREIGN KEY (department) REFERENCES public.departments(name),
  CONSTRAINT counseling_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.courses (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  department_id bigint,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  capacity integer DEFAULT 100,
  application_limit integer DEFAULT 200,
  status text DEFAULT 'Open'::text,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.departments (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.enrolled_students (
  student_id text NOT NULL UNIQUE,
  is_used boolean DEFAULT false,
  assigned_to_email text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  course text,
  status text DEFAULT 'Pending'::text,
  year_level text,
  CONSTRAINT enrolled_students_pkey PRIMARY KEY (student_id),
  CONSTRAINT enrolled_students_course_fkey FOREIGN KEY (course) REFERENCES public.courses(name)
);
CREATE TABLE public.event_attendance (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  event_id bigint,
  student_id text NOT NULL,
  student_name text,
  checked_in_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  time_in timestamp with time zone,
  time_out timestamp with time zone,
  proof_url text,
  latitude double precision,
  longitude double precision,
  department text,
  CONSTRAINT event_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendance_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_attendance_department_fkey FOREIGN KEY (department) REFERENCES public.departments(name),
  CONSTRAINT event_attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.event_feedback (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  event_id bigint,
  student_id text NOT NULL,
  student_name text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  sex text,
  college text,
  date_of_activity date,
  q1_score integer,
  q2_score integer,
  q3_score integer,
  q4_score integer,
  q5_score integer,
  q6_score integer,
  q7_score integer,
  open_best text,
  open_suggestions text,
  open_comments text,
  CONSTRAINT event_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT event_feedback_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_feedback_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.events (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  title text NOT NULL,
  type text NOT NULL,
  description text,
  location text,
  event_date date,
  event_time text,
  attendees bigint DEFAULT 0,
  end_time time without time zone,
  latitude double precision,
  longitude double precision,
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.forms (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT forms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.general_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id text NOT NULL,
  student_name text NOT NULL,
  client_type text,
  sex text,
  age integer,
  region text,
  service_availed text,
  cc1 integer,
  cc2 integer,
  cc3 integer,
  sqd0 integer,
  sqd1 integer,
  sqd2 integer,
  sqd3 integer,
  sqd4 integer,
  sqd5 integer,
  sqd6 integer,
  sqd7 integer,
  sqd8 integer,
  suggestions text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT general_feedback_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nat_requirements (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT nat_requirements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_id text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.office_visit_reasons (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  reason text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT office_visit_reasons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.office_visits (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  student_id text,
  student_name text,
  reason text,
  time_in timestamp with time zone DEFAULT now(),
  time_out timestamp with time zone,
  status text DEFAULT 'Ongoing'::text,
  CONSTRAINT office_visits_pkey PRIMARY KEY (id),
  CONSTRAINT office_visits_reason_fkey FOREIGN KEY (reason) REFERENCES public.office_visit_reasons(reason),
  CONSTRAINT office_visits_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.questions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  form_id bigint,
  question_text text NOT NULL,
  question_type text DEFAULT 'scale'::text,
  scale_min integer DEFAULT 1,
  scale_max integer DEFAULT 5,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['Admin'::character varying, 'Care Staff'::character varying, 'Department Head'::character varying, 'Student'::character varying, 'Public'::character varying]::text[])),
  permission_type character varying NOT NULL CHECK (permission_type::text = ANY (ARRAY['table'::character varying, 'function'::character varying, 'feature'::character varying, 'action'::character varying]::text[])),
  permission_key character varying NOT NULL CHECK (length(btrim(permission_key::text)) > 0),
  is_allowed boolean NOT NULL DEFAULT true,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_by bigint DEFAULT (NULLIF(current_staff_account_id(), ''::text))::bigint,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  status character varying NOT NULL DEFAULT 'enabled'::character varying CHECK (status::text = ANY (ARRAY['enabled'::character varying, 'hidden'::character varying, 'maintenance'::character varying, 'coming_soon'::character varying]::text[])),
  notice_text text,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.staff_accounts(id)
);
CREATE TABLE public.scholarship_applications (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  scholarship_id bigint NOT NULL,
  student_id text NOT NULL,
  status text DEFAULT 'Applied'::text,
  CONSTRAINT scholarship_applications_pkey PRIMARY KEY (id),
  CONSTRAINT scholarship_applications_scholarship_id_fkey FOREIGN KEY (scholarship_id) REFERENCES public.scholarships(id),
  CONSTRAINT scholarship_applications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.scholarships (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  title text NOT NULL,
  deadline date,
  description text,
  requirements text,
  CONSTRAINT scholarships_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_change_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['student'::text, 'staff'::text])),
  purpose text NOT NULL CHECK (purpose = ANY (ARRAY['password_change'::text, 'email_change'::text, 'destructive_reset'::text])),
  target_email text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  consumed_at timestamp with time zone,
  attempt_count integer NOT NULL DEFAULT 0,
  last_attempt_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT security_change_otps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff_accounts (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  username text NOT NULL UNIQUE,
  full_name text,
  role text NOT NULL,
  department text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  auth_user_id uuid UNIQUE,
  CONSTRAINT staff_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT staff_accounts_department_fkey FOREIGN KEY (department) REFERENCES public.departments(name)
);
CREATE TABLE public.student_activation_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  require_enrollment_key boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_by uuid,
  CONSTRAINT student_activation_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.students (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  first_name text NOT NULL,
  last_name text NOT NULL,
  student_id text NOT NULL UNIQUE,
  course text,
  year_level text,
  status text DEFAULT 'Active'::text,
  department text,
  middle_name text,
  dob date,
  civil_status text,
  nationality text,
  email text,
  mobile text,
  address text,
  emergency_contact text,
  street text,
  city text,
  province text,
  zip_code text,
  suffix text,
  place_of_birth text,
  age integer,
  sex text,
  gender_identity text,
  facebook_url text,
  school_last_attended text,
  is_working_student boolean DEFAULT false,
  working_student_type text,
  supporter text,
  supporter_contact text,
  is_pwd boolean DEFAULT false,
  pwd_type text,
  is_indigenous boolean DEFAULT false,
  indigenous_group text,
  witnessed_conflict boolean DEFAULT false,
  is_solo_parent boolean DEFAULT false,
  is_child_of_solo_parent boolean DEFAULT false,
  priority_course text,
  alt_course_1 text,
  alt_course_2 text,
  section text DEFAULT ''::text,
  profile_picture_url text,
  religion text,
  is_safe_in_community boolean DEFAULT false,
  mother_name text,
  mother_occupation text,
  mother_contact text,
  father_name text,
  father_occupation text,
  father_contact text,
  parent_address text,
  num_brothers text,
  num_sisters text,
  birth_order text,
  spouse_name text,
  spouse_occupation text,
  num_children text,
  guardian_name text,
  guardian_address text,
  guardian_contact text,
  guardian_relation text,
  emergency_name text,
  emergency_address text,
  emergency_relationship text,
  emergency_number text,
  elem_school text,
  elem_year_graduated text,
  junior_high_school text,
  junior_high_year_graduated text,
  senior_high_school text,
  senior_high_year_graduated text,
  college_school text,
  college_year_graduated text,
  honors_awards text,
  extracurricular_activities text,
  scholarships_availed text,
  profile_completed boolean DEFAULT false,
  has_seen_tour boolean DEFAULT false,
  course_year_update_required boolean NOT NULL DEFAULT false,
  course_year_window_start timestamp with time zone,
  course_year_window_end timestamp with time zone,
  course_year_confirmed_at timestamp with time zone,
  course_year_archive jsonb NOT NULL DEFAULT '[]'::jsonb,
  father_last_name text,
  father_given_name text,
  father_middle_name text,
  mother_last_name text,
  mother_given_name text,
  mother_middle_name text,
  auth_user_id uuid UNIQUE,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_department_fkey FOREIGN KEY (department) REFERENCES public.departments(name),
  CONSTRAINT students_course_fkey FOREIGN KEY (course) REFERENCES public.courses(name)
);
CREATE TABLE public.submissions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  form_id bigint,
  student_id text,
  submitted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT fk_submissions_students FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);
CREATE TABLE public.support_requests (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  student_id text NOT NULL,
  student_name text,
  department text,
  support_type text,
  description text,
  documents_url text,
  status text DEFAULT 'Submitted'::text,
  care_notes text,
  care_documents_url text,
  dept_notes text,
  resolution_notes text,
  CONSTRAINT support_requests_pkey PRIMARY KEY (id),
  CONSTRAINT support_requests_department_fkey FOREIGN KEY (department) REFERENCES public.departments(name),
  CONSTRAINT support_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(student_id)
);